//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restmium.ERP.Services.Warehouse.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restmium.ERP.Services.Warehouse.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete IssueSlip(Id={0}). IssueSlip not found!.
        /// </summary>
        public static string IssueSlip_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("IssueSlip_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move IssueSlip(Id={0}) to bin!.
        /// </summary>
        public static string IssueSlip_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("IssueSlip_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueSlip(Id={0}) not found!.
        /// </summary>
        public static string IssueSlip_EntityNotFoundException {
            get {
                return ResourceManager.GetString("IssueSlip_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update IssueSlip(Id={0}). IssueSlip not found!.
        /// </summary>
        public static string IssueSlip_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("IssueSlip_Update_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find entities for IssueSlip.Item(IssueSlipId={0}, WareId={1})!.
        /// </summary>
        public static string IssueSlipItem_EntitiesNotFoundException {
            get {
                return ResourceManager.GetString("IssueSlipItem_EntitiesNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move IssueSlip.Item(IssueSlipId={0}, PositionId={1}, WareId={2}) to bin!.
        /// </summary>
        public static string IssueSlipItem_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("IssueSlipItem_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueSlip.Item(IssueSlipId={0}, PositionId={1}, WareId={2}) not found!.
        /// </summary>
        public static string IssueSlipItem_EntityNotFoundException {
            get {
                return ResourceManager.GetString("IssueSlipItem_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueSlip.Item(IssueSlipId={0}, WareId={1}) has been fully assigned!.
        /// </summary>
        public static string IssueSlipItem_FullyAssignedException {
            get {
                return ResourceManager.GetString("IssueSlipItem_FullyAssignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueSlip.Item(IssueSlipId={0}, WareId={2}) is already assigned to Position(Id={1})!.
        /// </summary>
        public static string IssueSlipItem_PositionAlreadyAssignedException {
            get {
                return ResourceManager.GetString("IssueSlipItem_PositionAlreadyAssignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot issue units for IssueSlip.Item(IssueSlipId={0}, PositionId={1}, WareId={2}). Position doesn&apos;t hold enough units!.
        /// </summary>
        public static string IssueSlipItem_PositionAvailableUnitsException {
            get {
                return ResourceManager.GetString("IssueSlipItem_PositionAvailableUnitsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssueSlip.Item(IssueSlipId={0}, WareId={2}) cannot be assigned to Position(Id={1})! Position holds a different Ware!.
        /// </summary>
        public static string IssueSlipItem_PositionWareConflictException {
            get {
                return ResourceManager.GetString("IssueSlipItem_PositionWareConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot issue units for IssueSlip.Item(IssueSlipId={0}, PositionId={1}, WareId={2}). Requested units exceeded!.
        /// </summary>
        public static string IssueSlipItem_RequestedUnitsExceededException {
            get {
                return ResourceManager.GetString("IssueSlipItem_RequestedUnitsExceededException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Movement to retrieve Ware with Id={1} at Position with Id={2}. Position doesn&apos;t hold enough units!.
        /// </summary>
        public static string Movement_Create_PositionEmptyException {
            get {
                return ResourceManager.GetString("Movement_Create_PositionEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to store Ware ({0}) at Position ({1}) in amount of {2} units. Load capacity exceeded..
        /// </summary>
        public static string Movement_Create_PositionLoadCapacityException {
            get {
                return ResourceManager.GetString("Movement_Create_PositionLoadCapacityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to store Ware ({0}) at Position ({1}) in amount of {2} units. Space capacity exceeded..
        /// </summary>
        public static string Movement_Create_PositionSpaceCapacityException {
            get {
                return ResourceManager.GetString("Movement_Create_PositionSpaceCapacityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Movement to {0} Ware with Id={1} at Position with Id={2}. Position contains another Ware with Id={3}!.
        /// </summary>
        public static string Movement_Create_PositionWareConflictException {
            get {
                return ResourceManager.GetString("Movement_Create_PositionWareConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Movement(Id={0}). Movement not found!.
        /// </summary>
        public static string Movement_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Movement_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move Movement(Id={0}) to bin!.
        /// </summary>
        public static string Movement_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("Movement_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement(Id={0}) not found!.
        /// </summary>
        public static string Movement_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Movement_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Position(Id={0}). Position not found!.
        /// </summary>
        public static string Position_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Position_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Position(Id={0}). Position is not empty!.
        /// </summary>
        public static string Position_EntityDeleteException {
            get {
                return ResourceManager.GetString("Position_EntityDeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move Position(Id={0}) to bin!.
        /// </summary>
        public static string Position_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("Position_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position(Id={0}) not found!.
        /// </summary>
        public static string Position_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Position_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Position(Id={0}). Position not found!.
        /// </summary>
        public static string Position_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Position_Update_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Receipt(Id={0}). Receipt not found!.
        /// </summary>
        public static string Receipt_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Receipt_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt(Id={0}) not found!.
        /// </summary>
        public static string Receipt_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Receipt_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Receipt(Id={0}). Receipt not found!.
        /// </summary>
        public static string Receipt_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Receipt_Update_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Receipt.Item(Ware(ProductId={0}), Units={1}). Ware not found!.
        /// </summary>
        public static string ReceiptItem_Create_Ware_EntityNotFoundException {
            get {
                return ResourceManager.GetString("ReceiptItem_Create_Ware_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process Receipt.Item(ReceiptId={0}, WareId={1}). Warehouse is full!.
        /// </summary>
        public static string ReceiptItem_Create_WarehouseFullException {
            get {
                return ResourceManager.GetString("ReceiptItem_Create_WarehouseFullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find entities of Receipt.Item(ReceiptId={0}, WareId={1})!.
        /// </summary>
        public static string ReceiptItem_EntitiesNotFoundException {
            get {
                return ResourceManager.GetString("ReceiptItem_EntitiesNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move Receipt.Item(ReceiptId={0}, PositionId={1}, WareId={2}) to bin!.
        /// </summary>
        public static string ReceiptItem_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("ReceiptItem_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.Item(ReceiptId={0}, PositionId={1}, WareId={2}) not found!.
        /// </summary>
        public static string ReceiptItem_EntityNotFoundException {
            get {
                return ResourceManager.GetString("ReceiptItem_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.Item(ReceiptId={0}, WareId={1}) has been fully assigned!.
        /// </summary>
        public static string ReceiptItem_FullyAssignedException {
            get {
                return ResourceManager.GetString("ReceiptItem_FullyAssignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to store units for Receipt.Item(ReceiptId={0}, PositionId={1}, WareId={2}). Ordered units exceeded!.
        /// </summary>
        public static string ReceiptItem_OrderedUnitsExceededException {
            get {
                return ResourceManager.GetString("ReceiptItem_OrderedUnitsExceededException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.Item(ReceiptId={0}, WareId={2}) is already assigned to Position(Id={1})!.
        /// </summary>
        public static string ReceiptItem_PositionAlreadyAssignedException {
            get {
                return ResourceManager.GetString("ReceiptItem_PositionAlreadyAssignedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.Item(ReceiptId={0}, WareId={2}) cannot be assigned to Position(Id={1})! Position holds a different Ware!.
        /// </summary>
        public static string ReceiptItem_PositionWareConflictException {
            get {
                return ResourceManager.GetString("ReceiptItem_PositionWareConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Receipt.Item(ReceiptId={0}, WareId={1}). Receipt.Item not found!.
        /// </summary>
        public static string ReceiptItem_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("ReceiptItem_Update_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to relocate Wares from Position(Id={0}). Position is empty!.
        /// </summary>
        public static string Relocation_PositionEmptyException {
            get {
                return ResourceManager.GetString("Relocation_PositionEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to relocate Wares from Position(Id={0}) to Position(Id={1}). Load capacity exceeded!.
        /// </summary>
        public static string Relocation_PositionLoadCapacityException {
            get {
                return ResourceManager.GetString("Relocation_PositionLoadCapacityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to relocate Wares from Position(Id={0}) to Position(Id={1}). Positions store different Wares..
        /// </summary>
        public static string Relocation_PositionWareConflictException {
            get {
                return ResourceManager.GetString("Relocation_PositionWareConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Section(Id={0}). Section not found!.
        /// </summary>
        public static string Section_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Section_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move Section(Id={0}) to bin!.
        /// </summary>
        public static string Section_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("Section_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section(Id={0}) not found!.
        /// </summary>
        public static string Section_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Section_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Section(Id={0}). Section not found!.
        /// </summary>
        public static string Section_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Section_Update_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move StockTaking(Id={0}) to bin!.
        /// </summary>
        public static string StockTaking_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("StockTaking_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTaking(Id={0}) not found!.
        /// </summary>
        public static string StockTaking_EntityNotFoundException {
            get {
                return ResourceManager.GetString("StockTaking_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-Taking in Section(Id={0}).
        /// </summary>
        public static string StockTaking_Name_Section {
            get {
                return ResourceManager.GetString("StockTaking_Name_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-Taking in Warehouse(Id={0}).
        /// </summary>
        public static string StockTaking_Name_Warehouse {
            get {
                return ResourceManager.GetString("StockTaking_Name_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move StockTakingItem(StockTakingId={0}, PositionId={1}) to bin!.
        /// </summary>
        public static string StockTakingItem_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("StockTakingItem_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTaking.Item(StockTakingId={0}, PositionId={1}) not found!.
        /// </summary>
        public static string StockTakingItem_EntityNotFoundException {
            get {
                return ResourceManager.GetString("StockTakingItem_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Ware(Id={0}). Ware not found!.
        /// </summary>
        public static string Ware_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Ware_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create Ware(ProductId={0}). Ware already exists!.
        /// </summary>
        public static string Ware_EntityAlreadyExitsException {
            get {
                return ResourceManager.GetString("Ware_EntityAlreadyExitsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move Ware(Id={0}) to bin!.
        /// </summary>
        public static string Ware_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("Ware_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ware(Id={0}) not found!.
        /// </summary>
        public static string Ware_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Ware_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ware(ProductId={0}) not found!.
        /// </summary>
        public static string Ware_ProductId_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Ware_ProductId_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Ware(Id={0}). Ware not found!.
        /// </summary>
        public static string Ware_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Ware_Update_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete Warehouse(Id={0}). Warehouse not found!.
        /// </summary>
        public static string Warehouse_Delete_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Warehouse_Delete_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move Warehouse(Id={0}) to bin!.
        /// </summary>
        public static string Warehouse_EntityMoveToBinException {
            get {
                return ResourceManager.GetString("Warehouse_EntityMoveToBinException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse(Id={0}) not found!.
        /// </summary>
        public static string Warehouse_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Warehouse_EntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update Warehouse(Id={0}). Warehouse not found!.
        /// </summary>
        public static string Warehouse_Update_EntityNotFoundException {
            get {
                return ResourceManager.GetString("Warehouse_Update_EntityNotFoundException", resourceCulture);
            }
        }
    }
}
